version: "2.2"
services:
  sqlserver:
    image: metaskills/mssql-server-linux-rails
  ci:
    environment:
      - ACTIVERECORD_UNITTEST_HOST=sqlserver
    build:
      context: .
      dockerfile: Dockerfile.ci
    command: wait-for sqlserver:1433 -- ls
    depends_on:
      - "sqlserver"
